[build]
command = "astro build"
publish = "dist"

[[redirects]]
from = "/blog/*"
to = "https://sirlisko-blog.netlify.app/:splat"
status = 200

[[redirects]]
from = "/js/script.js"
to = "https://stats.sirlisko.com/js/script.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://stats.sirlisko.com/api/event"
status = 200
