[build]
command = "astro build"
publish = "dist"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
from = "/blog/*"
to = "https://sirlisko-blog.netlify.app/:splat"
status = 200

[[headers]]
  for = "/cv/private*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
