[build]
  command = "next build"
  publish = "out"

[[redirects]]
  from = "/blog/*"
  to = "https://blog.sirlisko.com/blog/:splat"
  status = 200

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
